[versions]
agp = "8.13.1"
googleApiClient = "2.8.1"
googleApiServicesSheets = "v4-rev20230815-2.0.0"
googleHttpClientGson = "2.0.2"
googleOauthClient = "1.39.0"
kotlin = "2.2.21"
kotlinxSerializationJson = "1.9.0"
okhttp = "5.3.2"
jetbrainsKotlinJvm = "2.2.21"
sqlite = "3.46.0.0"
slf4j = "2.0.12"

[libraries]
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-services-sheets = { module = "com.google.apis:google-api-services-sheets", version.ref = "googleApiServicesSheets" }
google-http-client-gson = { module = "com.google.http-client:google-http-client-gson", version.ref = "googleHttpClientGson" }
google-oauth-client = { module = "com.google.oauth-client:google-oauth-client", version.ref = "googleOauthClient" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

